# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_reglogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktitle', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewcontent', models.TextField(max_length=1000)),
                ('bookrating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookreview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookreviews', to='app_book.Book')),
                ('userreview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreviews', to='app_reglogin.User')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='bookauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookauthors', to='app_book.Book'),
        ),
    ]
