# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reglogin', '0001_initial'),
        ('app_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='userbook',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='userbook', to='app_reglogin.User'),
            preserve_default=False,
        ),
    ]
