# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0002_book_userbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='userbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbooks', to='app_reglogin.User'),
        ),
    ]
